In [ ]:
import numpy as np

A = np.array(
  [
    [1,2,3],
    [4,5,6],
    [7,8,9],
  ]
)

print("Matriks 3x3 : \n", A)

Matriks 3x3 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Soal 2
Definisikan dua matriks 2×2:


$$
\mathbf{A} = 
\begin{pmatrix} 1 & 2 \\ 3 & 4 
\end{pmatrix}$$

$$
\mathbf{B} = 
\begin{pmatrix} 5 & 6 \\ 7 & 8 
\end{pmatrix}$$

Hitung hasil penjumlahan dari kedua matriks tersebut.

In [3]:
import numpy as np

A = np.array(
  [
    [1,2],
    [3,4]
  ]
)

B = np.array(
  [
    [5,6],
    [7,8]
  ]
)

ans = A + B
print ("Hasil penjumlah matriks A dan Matriks B adalah : \n", ans)

Hasil penjumlah matriks A dan Matriks B adalah : 
 [[ 6  8]
 [10 12]]


## Soal 3

Hitunglah hasil perkalian matriks berikut:

$$
\mathbf{A} = 
\begin{pmatrix} 1 & 0 \\ 0 & 1 
\end{pmatrix}$$

$$
\mathbf{B} = 
\begin{pmatrix} 2 & 3 \\ 4 & 5 
\end{pmatrix}$$

Cetak hasilnya dalam bentuk matriks.


In [ ]:
import numpy as np

C = np.array(
  [
    [1,0],
    [0,1]
  ]
)

D = np.array(
  [
    [2,3],
    [4,5]
  ]
)

ans = np.dot(C,D)
print("Hasil perkalian antara matriks C dan D adalah : \n", ans)

## Soal 4

Diberikan matriks 2×3 berikut:


$$
\mathbf{E} = 
\begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 
\end{pmatrix}$$

Lakukan transpose dan cetak hasilnya.


In [ ]:
import numpy as np

E = np.array(
  [
    [1,2,3],
    [4,5,6]
  ]
)

trans_E = E.T
print("Transpose dari E adalah : \n", trans_E)

## Soal 5

Selesaikan sistem persamaan linier berikut menggunakan matriks:

𝓍 + 2𝓎 = 10

3𝓍 + 4𝓎 = 24


In [8]:
import numpy as np

A = np.array(
  [
    [1,2],
    [3,4]
  ]
)

B = np.array(
  [10,24]
)

inv_A = np.linalg.inv(A)
ans = np.dot(inv_A, B)
print("Nilai X dan Y dari persamaan tersebut yaitu : \n X =", ans[0], "\n Y =", ans[1])

Nilai X dan Y dari persamaan tersebut yaitu : 
 X = 3.9999999999999973 
 Y = 3.0000000000000013


## Soal 6
Diberikan dua matriks:

$$
\mathbf{A} = 
\begin{pmatrix} 1 & 2 \\ 3 & 4 
\end{pmatrix}$$

$$
\mathbf{B} = 
\begin{pmatrix} 5 & 6 \\ 7 & 8 
\end{pmatrix}$$

Gabungkan kedua matriks:

• Secara horizontal.

• Secara vertikal.

In [11]:
import numpy as np

A = np.array(
  [
    [1,2],
    [3,4]
  ]
)

B = np.array(
  [
    [5,6],
    [7,8]
  ]
)

ans_horizontal = np.hstack((A,B))
ans_vertical = np.vstack((A,B))

print("Hasil penggabungan antara matriks A dan B adalah : \n\n Horizontal : \n", ans_horizontal, "\n\n Vertical : \n", ans_vertical)

Hasil penggabungan antara matriks A dan B adalah : 

 Horizontal : 
 [[1 2 5 6]
 [3 4 7 8]] 

 Vertical : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Soal 7
Definisikan array 1D berikut:

$$
\mathbf{X} = 
\begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 
\end{pmatrix}$$

Ubah array tersebut menjadi matriks:

• Matriks 2×3

• Matriks 3×2

In [ ]:
import numpy as np

X = np.array(
  [
    [1,2,3],
    [4,5,6]
  ]
)

# X = np.array(
#   [1,2,3,4,5,6]
# )

matriks_2x3 = X.reshape(2,3)
matriks_3x2 = X.reshape(3,2)

print("Hasil dari perubahan bentuk matriksnya yaitu : \n\n Matriks 2x3 : \n", matriks_2x3, "\n\nMatriks 3x2 : \n", matriks_3x2)

Hasil dari perubahan bentuk matriksnya yaitu : 

 Matriks 2x3 : 
 [[1 2 3]
 [4 5 6]] 

Matriks 3x2 : 
 [[1 2]
 [3 4]
 [5 6]]
